-- MySQL Script generated by MySQL Workbench
-- Wed Nov 25 12:04:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cookbook
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cookbook` ;

-- -----------------------------------------------------
-- Schema cookbook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cookbook` DEFAULT CHARACTER SET utf8 ;
USE `cookbook` ;

-- -----------------------------------------------------
-- Table `cookbook`.`jidlo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cookbook`.`jidlo` ;

CREATE TABLE IF NOT EXISTS `cookbook`.`jidlo` (
  `idjidlo` INT NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(50) NOT NULL,
  `ingredience_jidlo` VARCHAR(45) NOT NULL,
  `recept` VARCHAR(5000) NOT NULL,
  PRIMARY KEY (`idjidlo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cookbook`.`ingredience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cookbook`.`ingredience` ;

CREATE TABLE IF NOT EXISTS `cookbook`.`ingredience` (
  `idingredience` INT NOT NULL AUTO_INCREMENT,
  `zelenina` VARCHAR(200) NULL,
  `ovoce` VARCHAR(200) NULL,
  `koreni` VARCHAR(200) NULL,
  `omacka` VARCHAR(200) NULL,
  `druh_masa` VARCHAR(45) NULL,
  `jidlo_idjidlo` INT NOT NULL,
  PRIMARY KEY (`idingredience`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
