-- MySQL Script generated by MySQL Workbench
-- Wed Nov 25 13:28:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cookbookv2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cookbookv2` ;

-- -----------------------------------------------------
-- Schema cookbookv2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cookbookv2` DEFAULT CHARACTER SET utf8 ;
USE `cookbookv2` ;

-- -----------------------------------------------------
-- Table `cookbookv2`.`jidlo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cookbookv2`.`jidlo` ;

CREATE TABLE IF NOT EXISTS `cookbookv2`.`jidlo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(50) NOT NULL,
  `ingredience` VARCHAR(1000) NOT NULL,
  `recept` VARCHAR(10000) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cookbookv2`.`ingredience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cookbookv2`.`ingredience` ;

CREATE TABLE IF NOT EXISTS `cookbookv2`.`ingredience` (
  `zelenina` VARCHAR(1000) NULL,
  `ovoce` VARCHAR(1000) NULL,
  `koreni` VARCHAR(1000) NULL,
  `omacka` VARCHAR(1000) NULL,
  `druh_masa` VARCHAR(1000) NULL,
  `jidlo_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`jidlo_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
