-- MySQL Script generated by MySQL Workbench
-- Wed Dec  2 11:01:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cookbook
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cookbook` ;

-- -----------------------------------------------------
-- Schema cookbook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cookbook` DEFAULT CHARACTER SET utf8 ;
USE `cookbook` ;

-- -----------------------------------------------------
-- Table `cookbook`.`jidlo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cookbook`.`jidlo` ;

CREATE TABLE IF NOT EXISTS `cookbook`.`jidlo` (
  `idjidlo` INT NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(50) NOT NULL,
  `ingredience` VARCHAR(1000) NOT NULL,
  `recept` VARCHAR(10000) NOT NULL,
  PRIMARY KEY (`idjidlo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
